/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BorderBox13: typeof import('./src/components/datav/border-box-13/border-box-13.vue')['default']
    CapsuleChart: typeof import('./src/components/datav/capsule-chart/capsule-chart.vue')['default']
    CountUp: typeof import('./src/components/count-up/count-up.vue')['default']
    EmptyCom: typeof import('./src/components/empty-com/empty-com.vue')['default']
    GlobalAlert: typeof import('./src/components/global-alert.vue')['default']
    HomeView: typeof import('./src/components/home-view.vue')['default']
    ItemWrap: typeof import('./src/components/item-wrap/item-wrap.vue')['default']
    MessageContent: typeof import('./src/components/Plugins/MessageContent/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleScreen: typeof import('./src/components/scale-screen/scale-screen.vue')['default']
    SeamlessScroll: typeof import('./src/components/seamless-scroll/seamless-scroll.vue')['default']
  }
}
